name: Build and Push Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    # https://github.com/vegardit/docker-gitea-act-runner/blob/main/.github/workflows/build.yml
    # vegardit/docker-gitea-act-runner 17时执行。在它之后执行。
    - cron: "0 18 * * *"

jobs:
  check-versions:
    runs-on: ubuntu-latest
    outputs:
      should-run: ${{ steps.compare.outputs.different }}
    steps:
      - name: Compare Docker Versions
        id: compare
        run: |
          version1=$(docker run --pull=always --rm --entrypoint act_runner yanhao98/gitea-act-runner --version)
          version2=$(docker run --pull=always --rm --entrypoint act_runner gitea/act_runner:nightly --version)
          different=$(test "$version1" != "$version2" && echo true || echo false)
          echo "version1=$version1"
          echo "version2=$version2"
          echo "different=$different"
          echo "different=$different" >> $GITHUB_OUTPUT

  build-and-push:
    needs: check-versions
    if: ${{ needs.check-versions.outputs.should-run == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: yanhao98/gitea-act-runner:latest
          platforms: linux/amd64,linux/arm64
